// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMKRVnsJIdewFVSzvc5g0ROe635TrmzQo',
    appId: '1:656359629176:web:50561f4577354d09d3288d',
    messagingSenderId: '656359629176',
    projectId: 'banaonotesapptask3',
    authDomain: 'banaonotesapptask3.firebaseapp.com',
    storageBucket: 'banaonotesapptask3.appspot.com',
    measurementId: 'G-2BTJFHQL5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVMXpEvxEQ_lTVynQA2pmK_fkKDsP7PMw',
    appId: '1:656359629176:android:bfc735ac97c24d52d3288d',
    messagingSenderId: '656359629176',
    projectId: 'banaonotesapptask3',
    storageBucket: 'banaonotesapptask3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfY6MP1IAezKc8FbLXP_J34s2KFWjIfUw',
    appId: '1:656359629176:ios:d87a34d3b9dd37ebd3288d',
    messagingSenderId: '656359629176',
    projectId: 'banaonotesapptask3',
    storageBucket: 'banaonotesapptask3.appspot.com',
    iosBundleId: 'com.example.banaoNotesAppTask3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfY6MP1IAezKc8FbLXP_J34s2KFWjIfUw',
    appId: '1:656359629176:ios:d56a8314c04cc2f6d3288d',
    messagingSenderId: '656359629176',
    projectId: 'banaonotesapptask3',
    storageBucket: 'banaonotesapptask3.appspot.com',
    iosBundleId: 'com.example.banaoNotesAppTask3.RunnerTests',
  );
}
